#!/bin/bash


##
#######################
## WEBMIN        ######
#######################
##
read -ep  "  $c2  install$green webmin? $re [y/n]: " -i "n" "webmin"
##
if [ $webmin == y ]; then echo "installing webmin";
wget https://download.webmin.com/devel/tarballs/webmin-current.tar.gz;
tar -xf webmin-current.tar.gz --strip-components=1; 
echo ; read -p "  -- Recommended port is$pink 2096$cyan Ok" okokokok;
./setup.sh /usr/local/webmin;
echo ; read -p "  -- Recommended port is$pink 2096$cyan Ok" okokokok;
ufw allow 2096
else echo "OK"; fi; cd $inst;
##
#######################
## WEBMIN - DONE ######
#######################
##


